#!/bin/bash

# convert input to "name."
rawName=$(echo $1 | sed 's/iso//')
rawName=$(echo $rawName | sed 's/.gz//')

echo Converting "$1" to "$rawName"chd...

gunzip $1

chdman createcd -i $(echo "$rawName"iso) -o $(echo "$rawName"chd)
rm "$rawName"iso
