#!/bin/bash

# convert input to "name."
rawName="$(echo $1 | sed 's/.iso/./')"
rawName="$(echo $rawName | sed 's/.zst//')"

echo Converting "$1" to "$rawName"chd...

unzstd --no-progress --rm "$1"

chdman createcd -i "$(echo "$rawName"iso)" -o "$(echo "$rawName"chd)"
rm "$rawName"iso
